#!/usr/bin/env bash
# We'll configure a new web server as we did before
# But adding a header variable with the host's name

# First we install Nginx and set up the HTTP
sudo apt update &&
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'

# Then set up index content
echo 'Holberton School for the win!' > /var/www/html/index.html

# Set up redirect_me
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'/etc/nginx/sites-available/default

# Display message in case error 404
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i '/listen 80 default_server/a error_page 404 /404.html;' /etc/nginx/sites-available/default

# Set the variable that will tell us which server is serving us
sed -i "/listen 80 default_server/a add_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default

# Run it!
service nginx start
